### ISSUE TITLE
Warnings on linux

### ISSUE THREAD

**Issue by acnazarejr** [smartsenselab/ssiglib#75]
/vagrant/modules/ml/src/kmeans.cpp:103:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int c = 0; c < mClusters.size(); ++c) {
                                          ^

/vagrant/modules/ml/src/spatial_pyramid.cpp: In static member function ‘static void ssig::SpatialPyramid::pool(const Size&, const std::vectorssig::Clustering*&, const std::vector<cv::Vec<int, 2> >&, const std::vector<float, std::allocator<float> >&, const std::vectorcv::Mat_<float >&, const std::vectorcv::Rect_<int >&, const std::vector<int>&, cv::Mat_<float>&)’:
/vagrant/modules/ml/src/spatial_pyramid.cpp:87:62: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int conf_it = 0; conf_it < pyramidConfigurations.size(); ++conf_it) {
                                                              ^
/vagrant/modules/ml/src/spatial_pyramid.cpp:93:55: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int part_it = 0; part_it < partFeatures.size(); ++part_it) {
                                                       ^
/vagrant/modules/ml/src/spatial_pyramid.cpp:106:64: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int model_it = 0; model_it < clusteringMethods.size(); ++model_it) {
                                                                ^
/vagrant/modules/ml/src/spatial_pyramid.cpp:118:63: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int weight_it = 0; weight_it < poolingWeights.size(); ++weight_it) {
                                                               ^

**Comment by rbkloss** [comment]
Fixed
